version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U todo
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "18080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: todo
      DB_USER: todo
      DB_PASSWORD: todo123
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/todo/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s

volumes:
  postgres_data: 